# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d83a3d75960e653b4282816b0d91f3ab8fbbb2a5b33ac998741c45de7b02687b2a4218e61aa5464a186763a44dc3f1bcce95755e093560015e2755aa99dc13cf

test:
  secret_key_base: 05b087c6850d5250d295cb4c0613c58ef1fc3aeaa68d3ee376e19ea26734d095fefd0d0d00c2b1e6ad911eaa994fbf625d4bc0da0253887081e61828b70bda4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
